<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
    <ProjectReference Include="../../../Aspire/EventHub.ServiceDefaults/EventHub.ServiceDefaults.csproj" />
    <ProjectReference Include="../../../Tools/EventHub.SeedData/EventHub.SeedData.csproj" />
    <ProjectReference Include="..\Booking.Application\Booking.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
